### ISSUE TITLE
Zygisk Enabled On Bluestacks But Not Detected By Shamiko module

### ISSUE THREAD

**Issue by slysnake96** [HuskyDG/MagiskOnEmu#14]
I have installed Magisk using your tool and have it working fine (I think) and I have turned on Zygisk, however when I load the Shamiko module it says that Zygisk is not enabled even though I have the Zygisk toggle turned on.
Please, any help would be greatly appreciated.

**Comment by HuskyDG** [comment]
Bluestacks cannot run Zygisk, you can see "Zygisk" is still "No" even you toggled on Zygisk and reboot, please use Mumu or NoxPlayer Android 9 emulator instead if you want Zygisk

**Comment by slysnake96** [comment]
Thank you for your help, I prefer using Bluestacks because it's easier for me to understand how it works because I have used it for a few years now.

**Comment by HuskyDG** [comment]
This problem is caused by Bluestacks or Magisk itself and i'm not capable of fixing it.
You can report this issue to Magisk github page but i am sure 100% topjohnwu developer of Magisk will not accept any issues related to Emulator

**Comment by slysnake96** [comment]
Ok thank you for your help and suggestions, I will look into Mumu because I really don't like Nox.

**Comment by HuskyDG** [comment]
> Ok thank you for your help and suggestions, I will look into Mumu because I really don't like Nox.

Same like this problem from actual devices, Zygisk cannot enable after reboot
https://github.com/topjohnwu/Magisk/issues/5353

I'm not sure it is related

**Comment by slysnake96** [comment]
I honestly don't understand much of that thread but i don't think it the same issue, with my issue it was that the Zygisk toggle turns on fine with no issues but the modules just cant detect it.

**Comment by HuskyDG** [comment]
> I honestly don't understand much of that thread but i don't think it the same issue, with my issue it was that the Zygisk toggle turns on fine with no issues but the modules just cant detect it.

This issue happens because zygote start earlier than pots-fs-data. That's mean Magisk zygisk's app_process is not replaced yet but zygote has started too early

**Comment by HuskyDG** [comment]
> I honestly don't understand much of that thread but i don't think it the same issue, with my issue it was that the Zygisk toggle turns on fine with no issues but the modules just cant detect it.

But you must pay attention to Zygisk status in main screen of Magisk app

**Comment by slysnake96** [comment]
In the main screen mine says NO so I guess it is the same or similar issue.
It was hard to tell what was happening in their screenshot since it said Nei which I believe is NO in Polish.

**Comment by slysnake96** [comment]
I'm sorry to bother you again but I have tried to install Magisk in Nox and all options in Magisk are greyed out, greyed out Superuser, greyed out Logs and greyed out Modules.
I followed your tutorial video but Magisk is still not working.
Magisk says this:
Installed: N/A
Ramdisk: Yes
A/B: No
SAR: No
Zygisk: No

Options I picked when installing Magisk:
Run with root: Y
1st Screen: option 1
Next Screen: Option 5
Next Screen: 1

**Comment by HuskyDG** [comment]
> I'm sorry to bother you again but I have tried to install Magisk in Nox and all options in Magisk are greyed out, greyed out Superuser, greyed out Logs and greyed out Modules. I followed your tutorial video but Magisk is still not working. Magisk says this: Installed: N/A Ramdisk: Yes A/B: No SAR: No Zygisk: No
> 
> Options I picked when installing Magisk: Run with root: Y 1st Screen: Option 1 Next Screen: Option 5 Next Screen: Option 1

Try Canary or Alpha build

**Comment by slysnake96** [comment]
I have tried Canary build it did the same thing I will now try Alpha build and let you know what happens.

**Comment by slysnake96** [comment]
I tried Alpha and got this after I typed /sbin/su
WARNING: linker: /sbin/magisk64: unsupported flags DT_FLAGS_1=0x8000001 read failed with 104: Connection reset by peer

**Comment by HuskyDG** [comment]
> I have tried Canary build it did the same thing I will now try Alpha build and let you know what happens.

Open new issue here so i can monitor the problem clearly

**Comment by slysnake96** [comment]
Ok will do

**Comment by HuskyDG** [comment]
> Do you try to install magisk on Wakuoo?

Mình chưa thử (I haven't tried yet)

**Comment by nguyenzzz** [comment]
> > Do you try to install magisk on Wakuoo?
> 
> Mình chưa thử (I haven't tried yet)

Tui nghĩ chắc ko cần test lắm. Vừa tải Wakuoo với Gameloop đều ko có phần cài apk hay nhập file. Root cho mấy giả lập này khá vô dụng :>
