### ISSUE TITLE
Magisk not working with Nox Android 7.1

### ISSUE THREAD

**Issue by slysnake96** [HuskyDG/MagiskOnEmu#15]
Magisk is not working correctly with Nox

**Comment by slysnake96** [comment]
I tried Alpha and got this after I typed /sbin/su
WARNING: linker: /sbin/magisk64: unsupported flags DT_FLAGS_1=0x8000001 read failed with 104: Connection reset by peer

**Comment by HuskyDG** [comment]
What is the Android version of Nox?

**Comment by slysnake96** [comment]
x64

**Comment by HuskyDG** [comment]
Oh please try Android 9, it will work

**Comment by slysnake96** [comment]
Where do I download the Android 9 version? Nox only lets you download that version even when you pick the android 9 beta

**Comment by slysnake96** [comment]
I have tried that but it still only downloads nox_setup_v7.0.2.1_full_intl.exe

**Comment by slysnake96** [comment]
that is what I have currently got installed

**Comment by slysnake96** [comment]
https://user-images.githubusercontent.com/5652
![Currently Installed Nox Version](https://user-images.githubusercontent.com/56527115/152394483-cd74a268-dc2b-4a85-a878-b2e49e7aa5ec.png)
7115/152394193-a5852274-0bd1-482e-bae0-fe81042eb5e2.mp4

I have attached a video showing that when I click on that link it doesn't download the correct one and a screenshot of the currently installed Nox version.

**Comment by HuskyDG** [comment]
> https://user-images.githubusercontent.com/5652 ![Currently Installed Nox Version](https://user-images.githubusercontent.com/56527115/152394483-cd74a268-dc2b-4a85-a878-b2e49e7aa5ec.png) 7115/152394193-a5852274-0bd1-482e-bae0-fe81042eb5e2.mp4
> 
> I have attached a video showing that when I click on that link it doesn't download the correct one and a screenshot of the currently installed Nox version.

Noxplayer version doesn't relate to Android version

**Comment by slysnake96** [comment]
How do I correctly check android version in Nox?
I went to android settings and looked at version down the bottom in Settings

**Comment by slysnake96** [comment]
![Android Version](https://user-images.githubusercontent.com/56527115/152395474-1605de78-7db3-4cd5-9096-82b115464c36.png)
This is what I see

**Comment by HuskyDG** [comment]
> How do I correctly check android version in Nox? I went to android settings and looked at version down the bottom in Settings

Can you record video to show me what you are doing.
Now it is midnight in my country and i need to sleep

**Comment by HuskyDG** [comment]
Or you can try Mumu Android 9 if you are still confuse

**Comment by slysnake96** [comment]
Ok I will keep trying to figure this out and will let you know in the morning how things go, I have taken enough of your time for today.
Thank you for continuing to help me figure this out :D

**Comment by slysnake96** [comment]
I figured out how to get Android 9 by reading this article attached.
[https://support.bignox.com/en/multi/android-version](url)

**Comment by slysnake96** [comment]
I followed your video tutorial after doing what I read in that article and Magisk is now working on Canary and also on Stable 24.1 also modules are now working correctly too and they are detecting Zygisk fine
