### ISSUE TITLE
v16.4(10039)-magisk-v24.1 install fail

### ISSUE THREAD

**Issue by MAYBreath** [HuskyDG/MagiskOnEmu#17]
stuck at the last line
Test on nox 9 64bit and ldplayer 7 all failed

**Comment by HuskyDG** [comment]
Just press Enter

**Comment by HuskyDG** [comment]
Android 7 LDPlayer Emulator will not support Magisk

**Comment by MAYBreath** [comment]
it‘s really have problem,plz don't close issue,
including v16.5 I test at Nox 9 64bit, 
v16.5 will not stuck at the last line anymore,but also don't install magisk apk ,.no magisk icon show at homedesk.

**Comment by HuskyDG** [comment]
> it‘s really have problem,plz don't close issue, including v16.5 I test at Nox 9 64bit, v16.5 will not stuck at the last line anymore,but also don't install magisk apk ,.no magisk icon show at homedesk.

Export magisk apk then install

**Comment by MAYBreath** [comment]
> > it‘s really have problem,plz don't close issue, including v16.5 I test at Nox 9 64bit, v16.5 will not stuck at the last line anymore,but also don't install magisk apk ,.no magisk icon show at homedesk.
> 
> Export magisk apk then install manually

I know that,but old version don't have that problem,and new one often cause Noxplayer crash or other strange bugs

**Comment by HuskyDG** [comment]
> > > it‘s really have problem,plz don't close issue, including v16.5 I test at Nox 9 64bit, v16.5 will not stuck at the last line anymore,but also don't install magisk apk ,.no magisk icon show at homedesk.
> > 
> > 
> > Export magisk apk then install manually
> 
> I know that,but old version don't have that problem,and new one often cause Noxplayer crash or other strange bugs

Try v16.6, now problem solved
