### ISSUE TITLE
10040 NOX7.0.2.1 Android9 Magisk doesn't install after I select option Install/Update Magisk

### ISSUE THREAD

**Issue by gunnicus** [HuskyDG/MagiskOnEmu#18]
NOX7.0.2.1
Android 9
v16.5(10040)-magisk-v24.1
This is the Android 9 I'm using from NoxPlayer:
![image](https://user-images.githubusercontent.com/4023477/154388342-449fa52a-bd82-4b96-a0c9-3aafdd87a598.png)
Installed latest release : v16.5(10040)-magisk-v24.1
![image](https://user-images.githubusercontent.com/4023477/154387856-2a9ce546-9d69-4f3f-a21c-8f4b0a9a4ad2.png)

![image](https://user-images.githubusercontent.com/4023477/154387898-32028ea7-949c-4da1-b3c8-a422a18360e8.png)

![image](https://user-images.githubusercontent.com/4023477/154387945-cc9af398-b991-4e1e-bea6-b98147525417.png)

![image](https://user-images.githubusercontent.com/4023477/154387974-487d7a89-d27e-4597-87d4-95949fd3c17d.png)

After that, it shows me Magisk: Not installed, there is no app icon of Magisk neither, If I reboot NoxPlayer, it stuck in reboot loop, I have to delete the instance. Please check.
![image](https://user-images.githubusercontent.com/4023477/154388046-36cabc88-bda1-4631-a22e-1e10f4a466ca.png)

![image](https://user-images.githubusercontent.com/4023477/154388125-363f86c7-15e0-4214-95b4-8bde9169ac59.png)

**Comment by HuskyDG** [comment]
Since 16.4, Magisk app will not be installed by default.
After Magisk installation, you need to export Magisk apk and install it manually

**Comment by gunnicus** [comment]
> Since 16.4, Magisk app will not be installed by default. After Magisk installation, you need to export Magisk apk and install it manually

Hi, thanks for your reply, I tried that but it shows me Unable to detect target image, Installation failed.
This is a fresh NoxPlayer and new Android 9 instance, did I miss anything? Thanks.
![image](https://user-images.githubusercontent.com/4023477/154390665-d1d3ec39-2219-4b26-9f08-f6e5cb672022.png)

![image](https://user-images.githubusercontent.com/4023477/154390723-57bbaf7e-4bbe-4800-8559-f711314fa7e7.png)
![image](https://user-images.githubusercontent.com/4023477/154390743-6a57bde9-ce71-4de0-b943-d4fabe77bc8f.png)

**Comment by HuskyDG** [comment]
> > Since 16.4, Magisk app will not be installed by default. After Magisk installation, you need to export Magisk apk and install it manually
> 
> Hi, thanks for your reply, I tried that but it shows me Unable to detect target image, Installation failed. This is a fresh NoxPlayer and new Android 9 instance, did I miss anything? Thanks. ![image](https://user-images.githubusercontent.com/4023477/154390665-d1d3ec39-2219-4b26-9f08-f6e5cb672022.png)
> 
> ![image](https://user-images.githubusercontent.com/4023477/154390723-57bbaf7e-4bbe-4800-8559-f711314fa7e7.png) ![image](https://user-images.githubusercontent.com/4023477/154390743-6a57bde9-ce71-4de0-b943-d4fabe77bc8f.png)

Die you understand me?????

**Comment by HuskyDG** [comment]
I said when you install Magisk from **Magisk on Android-x86**, Magisk app will not be installed.
After Magisk installation, you need to export Magisk apk and install it to manage root access and modules

**Comment by gunnicus** [comment]
Hi, After install, I choice option 'e' exported the .apk file
![image](https://user-images.githubusercontent.com/4023477/154394163-3ca91e15-b744-486f-a490-1a2a87db8e8d.png)
Then I goto Magisk folder found the .apk and run the .apk file, is this what you mean?
![image](https://user-images.githubusercontent.com/4023477/154394349-340724b8-c15d-44f6-8138-10238c2ebc22.png)

**Comment by HuskyDG** [comment]
> Hi, After install, I choice option 'e' exported the .apk file ![image](https://user-images.githubusercontent.com/4023477/154394163-3ca91e15-b744-486f-a490-1a2a87db8e8d.png) Then I goto Magisk folder found the .apk and run the .apk file, is this what you mean? ![image](https://user-images.githubusercontent.com/4023477/154394349-340724b8-c15d-44f6-8138-10238c2ebc22.png)

Install/Update Magisk -> Install Magisk into `/system` -> Export Magisk apk -> Install Magisk.apk

**Comment by gunnicus** [comment]
That's what I did, after reboot the Emulator stuck in reboot loop, I have to delete the instance.

**Comment by HuskyDG** [comment]
> That's what I did, after reboot the Emulator stuck in reboot loop, I have to delete the instance.

I have noticed about the problem. I am working on it now. Temporary you can use Magisk on NoxPlayer v16.3

**Comment by HuskyDG** [comment]
Fixed in v16.6
