### ISSUE TITLE
Magisk not installed

### ISSUE THREAD

**Issue by VanHoevenTR** [HuskyDG/MagiskOnEmu#19]
I'm using Nox 7.0.2.1 running Android 9 beta, but Magisk appear to not be installed after followed steps to install

![image](https://user-images.githubusercontent.com/70694330/154713300-116f554d-ff13-4448-afa2-70128130b90f.png)

**Comment by HuskyDG** [comment]
Sorry for late reply.  Since add Magisk into `/system/bin` systemlessly, Close NoxPlayer built-in root access accidentally remove MagiskSU.
Nox fix in https://github.com/HuskyDG/MagiskOnEmu/releases/tag/v10044

**Comment by VanHoevenTR** [comment]
Thanks very much, it works now

![image](https://user-images.githubusercontent.com/70694330/154809937-95b824ef-c810-4ff3-8770-887aa85b19c9.png)
