### ISSUE TITLE
Genymotion

### ISSUE THREAD

**Issue by skelletR** [HuskyDG/MagiskOnEmu#24]
Genymotion emulator work until android 8.1 but android 9 and 10 can't install
![Στιγμιότυπο οθόνης (320)](https://user-images.githubusercontent.com/25982450/157954465-2839c926-d022-4f45-a13a-24ac9af1c5e3.png)

**Comment by HuskyDG** [comment]
> Genymotion emulator work until android 8.1 but android 9 and 10 can't install ![IMG_20220311_163958](https://user-images.githubusercontent.com/25982450/157888853-99429a5a-a03a-4a43-a1dd-ae6ee218f9a2.jpg)

That might be your system partition is read-only!


Can you verify if system partition can be remounted as read-write?
```
mount -o rw,remount /system
```

**Comment by skelletR** [comment]
I checked and tell, but the genymotion android 8.1 work without need this

**Comment by skelletR** [comment]
> I checked and tell, but the genymotion android 8.1 work without need this

![Uploading IMG_20220311_215522.jpg…]()

**Comment by skelletR** [comment]
![Uploading IMG_20220311_215522.jpg…]()

**Comment by skelletR** [comment]
> > Genymotion emulator work until android 8.1 but android 9 and 10 can't install ![IMG_20220311_163958](https://user-images.githubusercontent.com/25982450/157888853-99429a5a-a03a-4a43-a1dd-ae6ee218f9a2.jpg)
> 
> That might be your system partition is read-only!
> 
> Can you verify if system partition can be remounted as read-write?
> 
> ```
> mount -o rw,remount /system
> ```

![Uploading IMG_20220311_215522.jpg…]()

**Comment by skelletR** [comment]
> > Genymotion emulator work until android 8.1 but android 9 and 10 can't install ![IMG_20220311_163958](https://user-images.githubusercontent.com/25982450/157888853-99429a5a-a03a-4a43-a1dd-ae6ee218f9a2.jpg)
> 
> That might be your system partition is read-only!
> 
> Can you verify if system partition can be remounted as read-write?
> 
> ```
> mount -o rw,remount /system
> ```
![Στιγμιότυπο οθόνης (321)](https://user-images.githubusercontent.com/25982450/157954792-7e050776-3e83-4305-8dd9-45c869f75850.png)

**Comment by HuskyDG** [comment]
> > > Genymotion emulator work until android 8.1 but android 9 and 10 can't install ![IMG_20220311_163958](https://user-images.githubusercontent.com/25982450/157888853-99429a5a-a03a-4a43-a1dd-ae6ee218f9a2.jpg)
> > 
> > 
> > That might be your system partition is read-only!
> > Can you verify if system partition can be remounted as read-write?
> > ```
> > mount -o rw,remount /system
> > ```
> 
> ![Στιγμιότυπο οθόνης (321)](https://user-images.githubusercontent.com/25982450/157954792-7e050776-3e83-4305-8dd9-45c869f75850.png)

Can i see the content of this command:
```
mount | grep " / "
```

**Comment by skelletR** [comment]
> > > > Genymotion emulator work until android 8.1 but android 9 and 10 can't install ![IMG_20220311_163958](https://user-images.githubusercontent.com/25982450/157888853-99429a5a-a03a-4a43-a1dd-ae6ee218f9a2.jpg)
> > > 
> > > 
> > > That might be your system partition is read-only!
> > > Can you verify if system partition can be remounted as read-write?
> > > ```
> > > mount -o rw,remount /system
> > > ```
> > 
> > 
> > ![Στιγμιότυπο οθόνης (321)](https://user-images.githubusercontent.com/25982450/157954792-7e050776-3e83-4305-8dd9-45c869f75850.png)
> 
> Can i see the content of this command:
> 
> ```
> mount | grep " / "
> ```
> 
> And
> 
> ```
> mount -o rw,remount /
> ```
![Στιγμιότυπο οθόνης (322)](https://user-images.githubusercontent.com/25982450/158015672-cbc4a224-b19b-44ce-9c95-f0375584052f.png)

**Comment by HuskyDG** [comment]
> > > > > Genymotion emulator work until android 8.1 but android 9 and 10 can't install ![IMG_20220311_163958](https://user-images.githubusercontent.com/25982450/157888853-99429a5a-a03a-4a43-a1dd-ae6ee218f9a2.jpg)
> > > > 
> > > > 
> > > > That might be your system partition is read-only!
> > > > Can you verify if system partition can be remounted as read-write?
> > > > ```
> > > > mount -o rw,remount /system
> > > > ```
> > > 
> > > 
> > > ![Στιγμιότυπο οθόνης (321)](https://user-images.githubusercontent.com/25982450/157954792-7e050776-3e83-4305-8dd9-45c869f75850.png)
> > 
> > 
> > Can i see the content of this command:
> > ```
> > mount | grep " / "
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And
> > ```
> > mount -o rw,remount /
> > ```
> 
> ![Στιγμιότυπο οθόνης (322)](https://user-images.githubusercontent.com/25982450/158015672-cbc4a224-b19b-44ce-9c95-f0375584052f.png)

Send me `mount.txt` file after this command:
```
mount >/sdcard/mount.txt
```

**Comment by skelletR** [comment]
[mount.txt](https://github.com/HuskyDG/MagiskOnEmu/files/8237560/mount.txt)

**Comment by HuskyDG** [comment]
> [mount.txt](https://github.com/HuskyDG/MagiskOnEmu/files/8237560/mount.txt)

After i had seen your mount info, i didn't see `/system` in your mount info so `/system` is not a mountpoint but it is a subfolder of `/`. So try remount `/` as read-write and then execute my script again!.

**Comment by skelletR** [comment]
> > [mount.txt](https://github.com/HuskyDG/MagiskOnEmu/files/8237560/mount.txt)
> 
> After i had seen your mount info, i didn't see `/system` in your mount info ➝ `/system` is not a mountpoint but it is a subfolder of `/`. So try remount `/` as read-write and then execute my script again!.

how do i do that? I try this mount -o rw,remount / not working

**Comment by skelletR** [comment]
All Work
