### ISSUE TITLE
AVD Emulator

### ISSUE THREAD

**Issue by skelletR** [HuskyDG/MagiskOnEmu#27]
![IMG_20220319_233400](https://user-images.githubusercontent.com/25982450/159139193-0fd09a99-193c-4a68-8d82-01e36937724c.jpg)
how do this? any instructions?

**Comment by HuskyDG** [comment]
I am going to use this script for patching ramdisk (replace init binary) instead of my current patching ramdisk script (patch init.rc)

**Comment by skelletR** [comment]
What you mean exactly? Now how can patch a ramdisk in avd?
