### ISSUE TITLE
Google Play services problem

### ISSUE THREAD

**Issue by Raffy2oo2** [HuskyDG/MagiskOnEmu#33]
After rooting with magisk the play store isnt wortking anymore and i cant pass the safetyNety, there is a way to solve this?

**Comment by AndnixSH** [comment]
Please provide more information (Android version, Magisk version, Magisk logs, Script logs...)
For SafetyNet, I suggest to read this https://github.com/HuskyDG/MagiskOnEmu/wiki/Can-Magisk-pass-SafetyNet-on-emulator%3F
